print_config: true
run:
  work_dir: /home/gulsum/Documents/Surrogates/schnetpack/src
  data_dir: /home/gulsum/Documents/Surrogates/schnetpack/src/data
  path: /home/gulsum/Documents/Surrogates/schnetpack/src/runs
  experiment: qm9_energy_U0
  id: Train0/curmodel
  ckpt_path: null
globals:
  model_path: best_model
  cutoff: 5.0
  lr: 0.0005
  property: energy_U0
  aggregation: sum
trainer:
  _target_: pytorch_lightning.Trainer
  devices: 1
  min_epochs: null
  max_epochs: 100000
  enable_model_summary: true
  profiler: null
  gradient_clip_val: 0
  accumulate_grad_batches: 1
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  fast_dev_run: false
  overfit_batches: 0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  detect_anomaly: false
  precision: 32
  accelerator: auto
  num_nodes: 1
  deterministic: false
  inference_mode: false
callbacks:
  model_checkpoint:
    _target_: schnetpack.train.ModelCheckpoint
    monitor: val_loss
    save_top_k: 1
    save_last: true
    mode: min
    verbose: false
    dirpath: checkpoints/
    filename: '{epoch:02d}'
    model_path: best_model
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val_loss
    patience: 200
    mode: min
    min_delta: 0.0
    check_on_train_epoch_end: false
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch
  ema:
    _target_: schnetpack.train.ExponentialMovingAverage
    decay: 0.995
task:
  _target_: schnetpack.AtomisticTask
  outputs:
  - _target_: schnetpack.task.ModelOutput
    name: energy_U0
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      rmse:
        _target_: torchmetrics.regression.MeanSquaredError
        squared: false
    loss_weight: 1.0
  warmup_steps: 0
  optimizer_cls: torch.optim.AdamW
  optimizer_args:
    lr: 0.0005
    weight_decay: 0.0
  scheduler_cls: schnetpack.train.ReduceLROnPlateau
  scheduler_monitor: val_loss
  scheduler_args:
    mode: min
    factor: 0.5
    patience: 75
    threshold: 0.0
    threshold_mode: rel
    cooldown: 10
    min_lr: 0.0
    smoothing_factor: 0.0
model:
  representation:
    radial_basis:
      _target_: schnetpack.nn.radial.GaussianRBF
      n_rbf: 20
      cutoff: 5.0
    _target_: schnetpack.representation.PaiNN
    n_atom_basis: 128
    n_interactions: 3
    shared_interactions: false
    shared_filters: false
    cutoff_fn:
      _target_: schnetpack.nn.cutoff.CosineCutoff
      cutoff: 5.0
  _target_: schnetpack.model.NeuralNetworkPotential
  input_modules:
  - _target_: schnetpack.atomistic.PairwiseDistances
  output_modules:
  - _target_: schnetpack.atomistic.Atomwise
    output_key: energy_U0
    n_in: 128
    aggregation_mode: sum
  postprocessors:
  - _target_: schnetpack.transform.CastTo64
  - _target_: schnetpack.transform.AddOffsets
    property: energy_U0
    add_mean: true
    add_atomrefs: true
data:
  _target_: schnetpack.datasets.QM9
  datapath: /home/gulsum/Documents/Surrogates/schnetpack/src/data/qm9.db
  data_workdir: null
  batch_size: 100
  num_train: 110000
  num_val: 10000
  num_test: null
  num_workers: 8
  num_val_workers: null
  num_test_workers: null
  train_sampler_cls: null
  remove_uncharacterized: true
  distance_unit: Ang
  property_units:
    energy_U0: eV
    energy_U: eV
    enthalpy_H: eV
    free_energy: eV
    homo: eV
    lumo: eV
    gap: eV
    zpve: eV
  transforms:
  - _target_: schnetpack.transform.SubtractCenterOfMass
  - _target_: schnetpack.transform.RemoveOffsets
    property: energy_U0
    remove_atomrefs: true
    remove_mean: true
  - _target_: schnetpack.transform.MatScipyNeighborList
    cutoff: 5.0
  - _target_: schnetpack.transform.CastTo32
logger:
  tensorboard:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: tensorboard/
    name: default
